src/java/usuarios/model/Usuario.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package usuarios.model;

/**
 *
 * @author R3oLoN
 */
public class Usuario {

    private Integer codigo;
    private String nome;
    private String usuario;
    private String senha;
    private String eMail;
    private String estado;
    private String cidade;

    public Usuario() {
    }

    public Usuario(Integer codigo, String nome, String usuario, String senha, String eMail, String estado, String cidade) {
        this.codigo = codigo;
        this.nome = nome;
        this.usuario = usuario;
        this.senha = senha;
        this.eMail = eMail;
        this.estado = estado;
        this.cidade = cidade;
    }

    public Integer getCodigo() {
        return codigo;
    }

    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }

    public String getNome() {
        return nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public String getUsuario() {
        return usuario;
    }

    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }

    public String getSenha() {
        return senha;
    }

    public void setSenha(String senha) {
        this.senha = senha;
    }

    public String getEMail() {
        return eMail;
    }

    public void setEMail(String eMail) {
        this.eMail = eMail;
    }

    public String getEstado() {
        return estado;
    }

    public void setEstado(String estado) {
        this.estado = estado;
    }

    public String getCidade() {
        return cidade;
    }

    public void setCidade(String cidade) {
        this.cidade = cidade;
    }

}

src/java/usuarios/managedbean/UsuarioMB.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package usuarios.managedbean;

import javax.annotation.PostConstruct;
import javax.faces.event.ValueChangeEvent;
import javax.faces.model.SelectItem;
import javax.faces.view.ViewScoped;
import javax.inject.Named;
import usuarios.model.Usuario;
import usuarios.utils.StringUtil;

/**
 *
 * @author R3oLoN
 */
@Named(value = "usuarioMB")
@ViewScoped
public class UsuarioMB {

    private static final SelectItem[] ESTADOS = new SelectItem[]{new SelectItem(null, " –- Selecione um Estado -– "),
        new SelectItem("SC", "Santa Catarina"), new SelectItem("PR", "Paraná "), new SelectItem("RS", "Rio Grande do Sul")};
    private static final SelectItem[] CIDADES_PR = new SelectItem[]{new SelectItem(null, "–Selecione uma Cidade–"),
        new SelectItem("CA", "Cascavel"), new SelectItem("CU", "Curitiba"), new SelectItem("FO", "Foz do Iguaçu")};
    private static final SelectItem[] CIDADES_RS = new SelectItem[]{new SelectItem(null, "–Selecione uma Cidade–"),
        new SelectItem("PA", "Porto Alegre"), new SelectItem("CS", "Caxias do Sul"), new SelectItem("PE", "Pelotas")};
    private static final SelectItem[] CIDADES_SC = new SelectItem[]{new SelectItem(null, "–Selecione uma Cidade–"),
        new SelectItem("FL", "Florianópolis"), new SelectItem("CR", "Criciúma"), new SelectItem("BL", "Blumenau")};

    private Usuario usuario;

    /**
     * Creates a new instance of UsuarioMB
     */
    public UsuarioMB() {
    }

    @PostConstruct
    private void initial() {
        usuario = new Usuario();
    }

    public Usuario getUsuario() {
        return usuario;
    }

    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    public SelectItem[] getEstados() {
        return UsuarioMB.ESTADOS;
    }

    public SelectItem[] getCidades() {
        if ("SC".equals(usuario.getEstado())) {
            return UsuarioMB.CIDADES_SC;
        } else if ("PR".equals(usuario.getEstado())) {
            return UsuarioMB.CIDADES_PR;
        } else if ("RS".equals(usuario.getEstado())) {
            return UsuarioMB.CIDADES_RS;
        }
        return null;
    }

    public void valueChangeListener(ValueChangeEvent event) {
        if (event.getNewValue() == null || event.getNewValue().equals(event.getOldValue()) || StringUtil.isEmpity(event.getComponent().getId())) {
            return;
        }
    }
}

web/index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>
        Hello from Facelets
    </h:body>
</html>

web/usuario.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>Cadastro de Usuário</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css"></link>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css"></link>
    </h:head>
    <h:body>
        <h:form class="form-horizontal">
            <f:attribute name="role" value="form" />
            <div class="jumbotron">
                <h1>Cadastro de usuário</h1>
            </div>
            <div class="container-fluid">
                <div class="form-group">
                    <label for="codigo" class="col-sm-2 control-label">Código: </label>
                    <div class="col-sm-6">
                        <h:inputText id="codigo" styleClass="form-control" value="#{usuarioMB.usuario.codigo}" disabled="true" />
                    </div>
                </div>
                <div class="form-group">
                    <label for="nome" class="col-sm-2 control-label">Nome: </label>
                    <div class="col-sm-6">
                        <h:inputText id="nome" styleClass="form-control" value="#{usuarioMB.usuario.nome}" />
                    </div>
                </div>
                <div class="form-group">
                    <label for="usuario" class="col-sm-2 control-label">Usuário: </label>
                    <div class="col-sm-6">
                        <h:inputText id="usuario" styleClass="form-control" value="#{usuarioMB.usuario.usuario}" />
                    </div>
                </div>
                <div class="form-group">
                    <label for="senha" class="col-sm-2 control-label">Senha: </label>
                    <div class="col-sm-6">
                        <h:inputText id="senha" styleClass="form-control" value="#{usuarioMB.usuario.senha}" />
                    </div>
                </div>
                <div class="form-group">
                    <label for="eMail" class="col-sm-2 control-label">E-mail: </label>
                    <div class="col-sm-6">
                        <h:inputText id="eMail" styleClass="form-control" value="#{usuarioMB.usuario.EMail}" />
                    </div>
                </div>
                <div class="form-group">
                    <label for="estados" class="col-sm-2 control-label">Estado: </label>
                    <div class="col-sm-6">
                        <h:selectOneMenu id="estados" styleClass="form-control" value="#{usuarioMB.usuario.estado}" valueChangeListener="#{usuarioMB.valueChangeListener}" onchange="submit();  ">
                            <f:selectItems value="#{usuarioMB.estados}" />
                        </h:selectOneMenu>
                    </div>
                </div>
                <div class="form-group">
                    <label for="cidade" class="col-sm-2 control-label">Cidade: </label>
                    <div class="col-sm-6">
                        <h:selectOneMenu id="cidade" styleClass="form-control" disabled="#{usuarioMB.usuario.estado == null}">
                            <f:selectItems value="#{usuarioMB.cidades}" />
                        </h:selectOneMenu>
                    </div>
                </div>
                <div class="col-sm-offset-2 btn-group btn-group-lg">
                    <button type="button" class="btn btn-default">Novo</button>
                    <button type="button" class="btn btn-primary">Salvar</button>
                    <button type="button" class="btn btn-warning">Excluir</button>
                </div>
            </div>
        </h:form>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
    </h:body>
</html>